parameters:
  StageSuffix: ''
stages:
- stage: Nodejs_Test_MacOS_${{ parameters.StageSuffix }}
  dependsOn:
  - Nodejs_Packaging
  condition: succeeded()
  jobs:
  - job: Nodejs_Test_MacOS_${{ parameters.StageSuffix }}
    workspace:
      clean: all
    timeoutInMinutes: 120
    pool:
      name: 'Azure Pipelines'
      image: 'macOS-13'
      os: 'macOS'

    variables:
    - name: OnnxRuntimeBuildDirectory
      value: '$(Build.BinariesDirectory)'
    steps:
    - template: test.yml
